<center>
<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M5_Final/images/SN_web_lightmode.png" width="300">
</center>

<h1>Analysis of Global COVID-19 Pandemic Data</h1>

Estimated time needed: **90** minutes

## Overview:

In this final project, you will apply your knowledge of data analysis by completing a series of hands-on tasks in this lab notebook. The lab consists of 10 tasks, where you will write and execute code to demonstrate your skills.

While working through the lab, remember to save all your code and outputs, then download the Jupyter Notebook, as you will need to submit the completed notebook for the **Final Project: Submission and Evaluation**.

If you need to refresh your memories about specific coding details, you may refer to previous hands-on labs for code examples.

In [ ]:
# This lab requires 'httr' and 'rvest'packages, which are already pre-loaded into this lab environment.
# However, if you are working on your local RStudio, please uncomment the below codes and install the packages.

#install.packages("httr")
#install.packages("rvest")

In [1]:
library(httr)
library(rvest)
print ("libraries are ready")

[1] "libraries are ready"

Note: if you can import above libraries, please use install.packages() to install them first.

## TASK 1: Get a `COVID-19 pandemic` Wiki page using HTTP request

First, let's write a function to use HTTP request to get a public COVID-19 Wiki page.

Before you write the function, you can open this public page from this 

URL https://en.wikipedia.org/w/index.php?title=Template:COVID-19_testing_by_country using a web browser.

The goal of task 1 is to get the html page using HTTP request (`httr` library)

In [2]:

get_wiki_covid19_page <- function() {
    
  # Our target COVID-19 wiki page URL is: https://en.wikipedia.org/w/index.php?title=Template:COVID-19_testing_by_country  
  # Which has two parts: 
    # 1) base URL `https://en.wikipedia.org/w/index.php  
    # 2) URL parameter: `title=Template:COVID-19_testing_by_country`, seperated by question mark ?
    
  # Wiki page base
  wiki_base_url <- "https://en.wikipedia.org/w/index.php"
  # You will need to create a List which has an element called `title` to specify which page you want to get from Wiki
  # in our case, it will be `Template:COVID-19_testing_by_country`
 
  # - Use the `GET` function in httr library with a `url` argument and a `query` arugment to get a HTTP response
    
  # Use the `return` function to return the response

}
print ("got wiki")

[1] "got wiki"

Call the `get_wiki_covid19_page` function to get a http response with the target html page

In [3]:
# Call the get_wiki_covid19_page function and print the response
get_wiki_covid19_page <- function() {
    
  # Wiki page base
  wiki_base_url <- "https://en.wikipedia.org/w/index.php"
  
  # Query parameters
  query_params <- list(
    title = "Template:COVID-19_testing_by_country"
  )
  
  # Send GET request
  response <- httr::GET(url = wiki_base_url, query = query_params)
  
  # Return response
  return(response)
}

# Call the function and print the response
response <- get_wiki_covid19_page()
print(response)

Response [https://en.wikipedia.org/w/index.php?title=Template%3ACOVID-19_testing_by_country]
  Date: 2026-05-11 17:56
  Status: 200
  Content-Type: text/html; charset=UTF-8
  Size: 457 kB
<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-fea...
<head>
<meta charset="UTF-8">
<title>Template:COVID-19 testing by country - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-heade...
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.st...
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return...
}];});});</script>
<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=ext.cite.styles%...
...

## TASK 2: Extract COVID-19 testing data table from the wiki HTML page

On the COVID-19 testing wiki page, you should see a data table `<table>` node contains COVID-19 testing data by country on the page:

<a href="https://cognitiveclass.ai/">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M5_Final/images/covid-19-by-country.png" width="400" align="center">
</a>

Note the numbers you actually see on your page may be different from above because it is still an on-going pandemic when creating this notebook.

The goal of task 2 is to extract above data table and convert it into a data frame

Now use the `read_html` function in rvest library to get the root html node from response

In [4]:
# Get the root html node from the http response in task 1 
# Load required libraries
library(httr)
library(xml2)

# Get the HTTP response
response <- get_wiki_covid19_page()

# Parse the response content and get the root HTML node
root_html <- read_html(response)

# Print the root HTML node
print(root_html)

{html_document}
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-theme-clientpref-thumb-standard" lang="en" dir="ltr">
[1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8 ...
[2] <body class="skin--responsive skin-vector skin-vector-search-vue mediawik ...

Get the tables in the HTML root node using `html_nodes` function.

In [5]:
# Get the table node from the root html node
# Load required library
library(rvest)

# Get the table node from the root HTML node
table_node <- html_node(root_html, "table")

# Print the table node
print(table_node)

{html_node}
<table class="box-Update plainlinks ombox ombox-content ambox-Update" role="presentation">
[1] <tbody><tr>\n<td class="mbox-image"><span typeof="mw:File"><span><img alt ...

Read the specific table from the multiple tables in the `table_node` using the `html_table` function and convert it into dataframe using `as.data.frame`

_Hint:- Please read the `table_node` with index 2(ex:- table_node[2])._

In [6]:
# Read the table node and convert it into a data frame, and print the data frame for review
# Read the table and convert it into a data frame
# covid_table <- html_table(table_node)

# FIX: extract all tables properly
tables <- html_table(root_html, fill = TRUE)
# original section     **************
# Select correct table
# covid_table <- tables[[1]]
# covid_df <- as.data.frame(covid_table)
# covid_df <- as.data.frame(covid_table, stringsAsFactors = FALSE)
# Print the data frame
# print(covid_df)
# View result
# print(clean_covid_df)
#  end of original section **********************
# Check all table dimensions
for(i in seq_along(tables)) {
  cat("\nTable", i, "dimensions:", dim(tables[[i]]), "\n")
}

# Select the table with enough columns
covid_table <- NULL

for(i in seq_along(tables)) {
  if(ncol(tables[[i]]) >= 7) {
    covid_table <- tables[[i]]
    break
  }
}

# Convert to dataframe
covid_df <- as.data.frame(covid_table, stringsAsFactors = FALSE)

print(head(covid_df))

Table 1 dimensions: 1 2

Table 2 dimensions: 173 9

Table 3 dimensions: 1 2

Table 4 dimensions: 1 5
    Country or region     Date[a]  Tested Units[b] Confirmed(cases)
1         Afghanistan 17 Dec 2020 154,767  samples           49,621
2             Albania 18 Feb 2021 428,654  samples           96,838
3             Algeria  2 Nov 2020 230,553  samples           58,574
4             Andorra 23 Feb 2022 300,307  samples           37,958
5              Angola  2 Feb 2021 399,228  samples           20,981
6 Antigua and Barbuda  6 Mar 2021  15,268  samples              832
  Confirmed /tested,% Tested /population,% Confirmed /population,%   Ref.
1                32.1                 0.40                    0.13    [1]
2                22.6                 15.0                     3.4    [2]
3                25.4                 0.53                    0.13 [3][4]
4                12.6                  387                    49.0    [5]
5                 5.3                  1.3                   0.067    [6]
6                 5.4                 15.9                    0.86    [7]

## TASK 3: Pre-process and export the extracted data frame

The goal of task 3 is to pre-process the extracted data frame from the previous step, and export it as a csv file

Let's get a summary of the data frame

In [7]:
# Print the summary of the data frame
summary(covid_df)
print ("task 3")

 Country or region    Date[a]             Tested            Units[b]
 Length:173         Length:173         Length:173         Length:173
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character
 Confirmed(cases)   Confirmed /tested,% Tested /population,%
 Length:173         Length:173          Length:173
 Class :character   Class :character    Class :character
 Mode  :character   Mode  :character    Mode  :character
 Confirmed /population,%     Ref.
 Length:173              Length:173
 Class :character        Class :character
 Mode  :character        Mode  :character

[1] "task 3"

As you can see from the summary, the columns names are little bit different to understand and some column data types are not correct. For example, the `Tested` column shows as `character`. 

As such, the data frame read from HTML table will need some pre-processing such as removing irrelvant columns, renaming columns, and convert columns into proper data types.

We have prepared a pre-processing function for you to conver the data frame but you can also try to write one by yourself

In [8]:
preprocess_covid_data_frame <- function(data_frame) {
    
    shape <- dim(data_frame)
    # Remove the World row
    # data_frame<-data_frame[!(data_frame$`Country.or.region`=="World"),]
    # Remove the last row
    # data_frame <- data_frame[1:172, ]
   # Remove World row if exists
    if ("Country.or.region" %in% colnames(data_frame)) {
      data_frame <- data_frame[!(data_frame$`Country.or.region` == "World"), ]  }
    # Keep only first 7 columns (fix structural mismatch)
    data_frame <- data_frame[, 1:7]
    # We dont need the Units and Ref columns, so can be removed
    data_frame["Ref."] <- NULL
    data_frame["Units.b."] <- NULL
    # Renaming the columns
    names(data_frame) <- c("country", "date", "tested", "confirmed", "confirmed.tested.ratio", "tested.population.ratio", "confirmed.population.ratio")
    # Convert column data types
    data_frame$country <- as.factor(data_frame$country)
    data_frame$date <- as.factor(data_frame$date)
# original code replaced ***** :
#    data_frame$tested <- as.numeric(gsub(",","",data_frame$tested))
#    data_frame$confirmed <- as.numeric(gsub(",","",data_frame$confirmed))
#    data_frame$'confirmed.tested.ratio' <- as.numeric(gsub(",","",data_frame$`confirmed.tested.ratio`))
#    data_frame$'tested.population.ratio' <- as.numeric(gsub(",","",data_frame$`tested.population.ratio`))
#    data_frame$'confirmed.population.ratio' <- as.numeric(gsub(",","",data_frame$`confirmed.population.ratio`))
# end of original code replacement *****

clean_numeric <- function(x) {
  # Convert to character
  x <- as.character(x)
  # Remove commas
  x <- gsub(",", "", x)
  # Remove percentage signs
  x <- gsub("%", "", x)
  # Remove footnotes like [a], [1], etc.
  x <- gsub("\\[.*?\\]", "", x)
  # Remove all non-numeric characters except decimal point
  x <- gsub("[^0-9\\.]", "", x)
  # Convert empty strings to NA
  x[x == ""] <- NA
  return(as.numeric(x))
}

# Apply cleaning
data_frame$tested <- clean_numeric(data_frame$tested)
data_frame$confirmed <- clean_numeric(data_frame$confirmed)
data_frame$confirmed.tested.ratio <- clean_numeric(
  data_frame$confirmed.tested.ratio)
data_frame$tested.population.ratio <- clean_numeric(
  data_frame$tested.population.ratio)
data_frame$confirmed.population.ratio <- clean_numeric(
  data_frame$confirmed.population.ratio)    
    
    return(data_frame)
}
print ("done")

[1] "done"

Call the `preprocess_covid_data_frame` function

In [9]:
# call `preprocess_covid_data_frame` function and assign it to a new data frame
clean_covid_df <- preprocess_covid_data_frame(covid_df)

print ("done")

Warning message in clean_numeric(data_frame$tested):
“NAs introduced by coercion”
Warning message in clean_numeric(data_frame$confirmed):
“NAs introduced by coercion”
Warning message in clean_numeric(data_frame$confirmed.tested.ratio):
“NAs introduced by coercion”
Warning message in clean_numeric(data_frame$tested.population.ratio):
“NAs introduced by coercion”
Warning message in clean_numeric(data_frame$confirmed.population.ratio):
“NAs introduced by coercion”

[1] "done"

Get the summary of the processed data frame again

In [10]:
# Print the summary of the processed data frame again
print(clean_covid_df)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       country
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Afghanistan
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Albania
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Algeria
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Andorra
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Angola
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Antigua and Barbuda
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Argentina
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Armenia
9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Australia

After pre-processing, you can see the columns and columns names are simplified, and columns types are converted into correct types.

The data frame has following columns:

- **country** - The name of the country
- **date** - Reported date
- **tested** - Total tested cases by the reported date
- **confirmed** - Total confirmed cases by the reported date
- **confirmed.tested.ratio** - The ratio of confirmed cases to the tested cases
- **tested.population.ratio** - The ratio of tested cases to the population of the country
- **confirmed.population.ratio** - The ratio of confirmed cases to the population of the country

OK, we can call `write.csv()` function to save the csv file into a file.

In [11]:
# Export the data frame to a csv file

Note for IBM Waston Studio, there is no traditional "hard disk" associated with a R workspace.

Even if you call `write.csv()` method to save the data frame as a csv file, it won't be shown in IBM Cloud Object Storage asset UI automatically.

However, you may still check if the `covid.csv` exists using following code snippet:

In [12]:
# Get working directory
wd <- getwd()
# Get exported 
file_path <- paste(wd, sep="", "/covid.csv")
# File path
print(file_path)
file.exists(file_path)

[1] "/resources/RP0101EN/labs/M5/covid.csv"

[1] TRUE

**Optional Step**: If you have difficulties finishing above webscraping tasks, you may still continue with next tasks by downloading a provided csv file from here:

In [13]:
## Download a sample csv file
# covid_csv_file <- download.file("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/dataset/covid.csv", destfile="covid.csv")
# covid_data_frame_csv <- read.csv("covid.csv", header=TRUE, sep=",")

## TASK 4: Get a subset of the extracted data frame

The goal of task 4 is to get the 5th to 10th rows from the data frame with only `country` and `confirmed` columns selected

In [14]:
# Read covid_data_frame_csv from the csv file
# Export dataframe first
write.csv(clean_covid_df, file = file_path, row.names = FALSE)
# Read CSV file
covid_data_frame_csv <- read.csv(file_path, header = TRUE)
# Print first rows
head(covid_data_frame_csv)

# Get the 5th to 10th rows, with two "country" "confirmed" columns
covid_data_frame_csv[5:10, c("country", "confirmed")]

  country             date        tested confirmed confirmed.tested.ratio
1 Afghanistan         17 Dec 2020 154767 NA        49621
2 Albania             18 Feb 2021 428654 NA        96838
3 Algeria             2 Nov 2020  230553 NA        58574
4 Andorra             23 Feb 2022 300307 NA        37958
5 Angola              2 Feb 2021  399228 NA        20981
6 Antigua and Barbuda 6 Mar 2021   15268 NA          832
  tested.population.ratio confirmed.population.ratio
1 32.1                      0.40
2 22.6                     15.00
3 25.4                      0.53
4 12.6                    387.00
5  5.3                      1.30
6  5.4                     15.90

   country             confirmed
5  Angola              NA
6  Antigua and Barbuda NA
7  Argentina           NA
8  Armenia             NA
9  Australia           NA
10 Austria             NA

## TASK 5: Calculate worldwide COVID testing positive ratio

The goal of task 5 is to get the total confirmed and tested cases worldwide, and try to figure the overall positive ratio using `confirmed cases / tested cases`

In [15]:
# Get the total confirmed cases worldwide
total_confirmed <- sum(
  covid_data_frame_csv$confirmed,
  na.rm = TRUE
)
print(total_confirmed)

# Get the total tested cases worldwide
total_tested <- sum(
  covid_data_frame_csv$tested,
  na.rm = TRUE
)
print(total_tested)

# Get the positive ratio (confirmed / tested)
positive_ratio <- total_confirmed / total_tested
print(positive_ratio)

[1] 0
[1] 5396881644
[1] 0

## TASK 6: Get a country list which reported their testing data 

The goal of task 6 is to get a catalog or sorted list of countries who have reported their COVID-19 testing data

In [16]:
# Get the `country` column
country_column <- covid_data_frame_csv$country
print(country_column)

# Check its class (should be character)
class(country_column)

# Sort the countries AtoZ
countries_atoz <- sort(country_column)
print(countries_atoz)

# Sort the countries ZtoA
countries_ztoa <- sort(country_column, decreasing = TRUE)
print(countries_ztoa)

# Print the sorted ZtoA list
print(countries_ztoa)

  [1] "Afghanistan"
  [2] "Albania"
  [3] "Algeria"
  [4] "Andorra"
  [5] "Angola"
  [6] "Antigua and Barbuda"
  [7] "Argentina"
  [8] "Armenia"
  [9] "Australia"
 [10] "Austria"
 [11] "Azerbaijan"
 [12] "Bahamas"
 [13] "Bahrain"
 [14] "Bangladesh"
 [15] "Barbados"
 [16] "Belarus"
 [17] "Belgium"
 [18] "Belize"
 [19] "Benin"
 [20] "Bhutan"
 [21] "Bolivia"
 [22] "Bosnia and Herzegovina"
 [23] "Botswana"
 [24] "Brazil"
 [25] "Brunei"
 [26] "Bulgaria"
 [27] "Burkina Faso"
 [28] "Burundi"
 [29] "Cambodia"
 [30] "Cameroon"
 [31] "Canada"
 [32] "Chad"
 [33] "Chile"
 [34] "China[c]"
 [35] "Colombia"
 [36] "Costa Rica"
 [37] "Croatia"
 [38] "Cuba"
 [39] "Cyprus[d]"
 [40] "Czechia"
 [41] "Denmark[e]"
 [42] "Djibouti"
 [43] "Dominica"
 [44] "Dominican Republic"
 [45] "DR Congo"
 [46] "Ecuador"
 [47] "Egypt"
 [48] "El Salvador"
 [49] "Equatorial Guinea"
 [50] "Estonia"
 [51] "Eswatini"
 [52] "Ethiopia"
 [53] "Faroe Islands"
 [54] "Fiji"
 [55] "Finland"
 [56] "France[f][g]"
 [57] "Gabon"
 [58] "Gambia"
 [59] "Georgia[h]"
 [60] "Germany"
 [61] "Ghana"
 [62] "Greece"
 [63] "Greenland"
 [64] "Grenada"
 [65] "Guatemala"
 [66] "Guinea"
 [67] "Guinea-Bissau"
 [68] "Guyana"
 [69] "Haiti"
 [70] "Honduras"
 [71] "Hungary"
 [72] "Iceland"
 [73] "India"
 [74] "Indonesia"
 [75] "Iran"
 [76] "Iraq"
 [77] "Ireland"
 [78] "Israel"
 [79] "Italy"
 [80] "Ivory Coast"
 [81] "Jamaica"
 [82] "Japan"
 [83] "Jordan"
 [84] "Kazakhstan"
 [85] "Kenya"
 [86] "Kosovo"
 [87] "Kuwait"
 [88] "Kyrgyzstan"
 [89] "Laos"
 [90] "Latvia"
 [91] "Lebanon"
 [92] "Lesotho"
 [93] "Liberia"
 [94] "Libya"
 [95] "Lithuania"
 [96] "Luxembourg[i]"
 [97] "Madagascar"
 [98] "Malawi"
 [99] "Malaysia"
[100] "Maldives"
[101] "Mali"
[102] "Malta"
[103] "Mauritania"
[104] "Mauritius"
[105] "Mexico"
[106] "Moldova[j]"
[107] "Mongolia"
[108] "Montenegro"
[109] "Morocco"
[110] "Mozambique"
[111] "Myanmar"
[112] "Namibia"
[113] "Nepal"
[114] "Netherlands"
[115] "New Caledonia"
[116] "New Zealand"
[117] "Niger"
[118] "Nigeria"
[119] "North Korea"
[120] "North Macedonia"
[121] "Northern Cyprus[k]"
[122] "Norway"
[123] "Oman"
[124] "Pakistan"
[125] "Palestine"
[126] "Panama"
[127] "Papua New Guinea"
[128] "Paraguay"
[129] "Peru"
[130] "Philippines"
[131] "Poland"
[132] "Portugal"
[133] "Qatar"
[134] "Romania"
[135] "Russia"
[136] "Rwanda"
[137] "Saint Kitts and Nevis"
[138] "Saint Lucia"
[139] "Saint Vincent"
[140] "San Marino"
[141] "Saudi Arabia"
[142] "Senegal"
[143] "Serbia"
[144] "Singapore"
[145] "Slovakia"
[146] "Slovenia"
[147] "South Africa"
[148] "South Korea"
[149] "South Sudan"
[150] "Spain"
[151] "Sri Lanka"
[152] "Sudan"
[153] "Sweden"
[154] "Switzerland[l]"
[155] "Taiwan[m]"
[156] "Tanzania"
[157] "Thailand"
[158] "Togo"
[159] "Trinidad and Tobago"
[160] "Tunisia"
[161] "Turkey"
[162] "Uganda"
[163] "Ukraine"
[164] "United Arab Emirates"
[165] "United Kingdom"
[166] "United States"
[167] "Uruguay"
[168] "Uzbekistan"
[169] "Venezuela"
[170] "Vietnam"
[171] "Zambia"
[172] "Zimbabwe"
[173] ".mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}body.skin-vector-2022 .mw-parser-output .reflist-columns-2{column-width:27em}body.skin-vector-2022 .mw-parser-output .reflist-columns-3{column-width:22.5em}.mw-parser-output .references[data-mw-group=upper-alpha]{list-style-type:upper-alpha}.mw-parser-output .references[data-mw-group=upper-roman]{list-style-type:upper-roman}.mw-parser-output .references[data-mw-group=lower-alpha]{list-style-type:lower-alpha}.mw-parser-output .references[data-mw-group=lower-greek]{list-style-type:lower-greek}.mw-parser-output .references[data-mw-group=lower-roman]{list-style-type:lower-roman}.mw-parser-output div.reflist-liststyle-upper-alpha .references{list-style-type:upper-alpha}.mw-parser-output div.reflist-liststyle-upper-roman .references{list-style-type:upper-roman}.mw-parser-output div.reflist-liststyle-lower-alpha .references{list-style-type:lower-alpha}.mw-parser-output div.reflist-liststyle-lower-greek .references{list-style-type:lower-greek}.mw-parser-output div.reflist-liststyle-lower-roman .references{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member."

[1] "character"

  [1] ".mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}body.skin-vector-2022 .mw-parser-output .reflist-columns-2{column-width:27em}body.skin-vector-2022 .mw-parser-output .reflist-columns-3{column-width:22.5em}.mw-parser-output .references[data-mw-group=upper-alpha]{list-style-type:upper-alpha}.mw-parser-output .references[data-mw-group=upper-roman]{list-style-type:upper-roman}.mw-parser-output .references[data-mw-group=lower-alpha]{list-style-type:lower-alpha}.mw-parser-output .references[data-mw-group=lower-greek]{list-style-type:lower-greek}.mw-parser-output .references[data-mw-group=lower-roman]{list-style-type:lower-roman}.mw-parser-output div.reflist-liststyle-upper-alpha .references{list-style-type:upper-alpha}.mw-parser-output div.reflist-liststyle-upper-roman .references{list-style-type:upper-roman}.mw-parser-output div.reflist-liststyle-lower-alpha .references{list-style-type:lower-alpha}.mw-parser-output div.reflist-liststyle-lower-greek .references{list-style-type:lower-greek}.mw-parser-output div.reflist-liststyle-lower-roman .references{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member."
  [2] "Afghanistan"
  [3] "Albania"
  [4] "Algeria"
  [5] "Andorra"
  [6] "Angola"
  [7] "Antigua and Barbuda"
  [8] "Argentina"
  [9] "Armenia"
 [10] "Australia"
 [11] "Austria"
 [12] "Azerbaijan"
 [13] "Bahamas"
 [14] "Bahrain"
 [15] "Bangladesh"
 [16] "Barbados"
 [17] "Belarus"
 [18] "Belgium"
 [19] "Belize"
 [20] "Benin"
 [21] "Bhutan"
 [22] "Bolivia"
 [23] "Bosnia and Herzegovina"
 [24] "Botswana"
 [25] "Brazil"
 [26] "Brunei"
 [27] "Bulgaria"
 [28] "Burkina Faso"
 [29] "Burundi"
 [30] "Cambodia"
 [31] "Cameroon"
 [32] "Canada"
 [33] "Chad"
 [34] "Chile"
 [35] "China[c]"
 [36] "Colombia"
 [37] "Costa Rica"
 [38] "Croatia"
 [39] "Cuba"
 [40] "Cyprus[d]"
 [41] "Czechia"
 [42] "Denmark[e]"
 [43] "Djibouti"
 [44] "Dominica"
 [45] "Dominican Republic"
 [46] "DR Congo"
 [47] "Ecuador"
 [48] "Egypt"
 [49] "El Salvador"
 [50] "Equatorial Guinea"
 [51] "Estonia"
 [52] "Eswatini"
 [53] "Ethiopia"
 [54] "Faroe Islands"
 [55] "Fiji"
 [56] "Finland"
 [57] "France[f][g]"
 [58] "Gabon"
 [59] "Gambia"
 [60] "Georgia[h]"
 [61] "Germany"
 [62] "Ghana"
 [63] "Greece"
 [64] "Greenland"
 [65] "Grenada"
 [66] "Guatemala"
 [67] "Guinea"
 [68] "Guinea-Bissau"
 [69] "Guyana"
 [70] "Haiti"
 [71] "Honduras"
 [72] "Hungary"
 [73] "Iceland"
 [74] "India"
 [75] "Indonesia"
 [76] "Iran"
 [77] "Iraq"
 [78] "Ireland"
 [79] "Israel"
 [80] "Italy"
 [81] "Ivory Coast"
 [82] "Jamaica"
 [83] "Japan"
 [84] "Jordan"
 [85] "Kazakhstan"
 [86] "Kenya"
 [87] "Kosovo"
 [88] "Kuwait"
 [89] "Kyrgyzstan"
 [90] "Laos"
 [91] "Latvia"
 [92] "Lebanon"
 [93] "Lesotho"
 [94] "Liberia"
 [95] "Libya"
 [96] "Lithuania"
 [97] "Luxembourg[i]"
 [98] "Madagascar"
 [99] "Malawi"
[100] "Malaysia"
[101] "Maldives"
[102] "Mali"
[103] "Malta"
[104] "Mauritania"
[105] "Mauritius"
[106] "Mexico"
[107] "Moldova[j]"
[108] "Mongolia"
[109] "Montenegro"
[110] "Morocco"
[111] "Mozambique"
[112] "Myanmar"
[113] "Namibia"
[114] "Nepal"
[115] "Netherlands"
[116] "New Caledonia"
[117] "New Zealand"
[118] "Niger"
[119] "Nigeria"
[120] "North Korea"
[121] "North Macedonia"
[122] "Northern Cyprus[k]"
[123] "Norway"
[124] "Oman"
[125] "Pakistan"
[126] "Palestine"
[127] "Panama"
[128] "Papua New Guinea"
[129] "Paraguay"
[130] "Peru"
[131] "Philippines"
[132] "Poland"
[133] "Portugal"
[134] "Qatar"
[135] "Romania"
[136] "Russia"
[137] "Rwanda"
[138] "Saint Kitts and Nevis"
[139] "Saint Lucia"
[140] "Saint Vincent"
[141] "San Marino"
[142] "Saudi Arabia"
[143] "Senegal"
[144] "Serbia"
[145] "Singapore"
[146] "Slovakia"
[147] "Slovenia"
[148] "South Africa"
[149] "South Korea"
[150] "South Sudan"
[151] "Spain"
[152] "Sri Lanka"
[153] "Sudan"
[154] "Sweden"
[155] "Switzerland[l]"
[156] "Taiwan[m]"
[157] "Tanzania"
[158] "Thailand"
[159] "Togo"
[160] "Trinidad and Tobago"
[161] "Tunisia"
[162] "Turkey"
[163] "Uganda"
[164] "Ukraine"
[165] "United Arab Emirates"
[166] "United Kingdom"
[167] "United States"
[168] "Uruguay"
[169] "Uzbekistan"
[170] "Venezuela"
[171] "Vietnam"
[172] "Zambia"
[173] "Zimbabwe"
  [1] "Zimbabwe"
  [2] "Zambia"
  [3] "Vietnam"
  [4] "Venezuela"
  [5] "Uzbekistan"
  [6] "Uruguay"
  [7] "United States"
  [8] "United Kingdom"
  [9] "United Arab Emirates"
 [10] "Ukraine"
 [11] "Uganda"
 [12] "Turkey"
 [13] "Tunisia"
 [14] "Trinidad and Tobago"
 [15] "Togo"
 [16] "Thailand"
 [17] "Tanzania"
 [18] "Taiwan[m]"
 [19] "Switzerland[l]"
 [20] "Sweden"
 [21] "Sudan"
 [22] "Sri Lanka"
 [23] "Spain"
 [24] "South Sudan"
 [25] "South Korea"
 [26] "South Africa"
 [27] "Slovenia"
 [28] "Slovakia"
 [29] "Singapore"
 [30] "Serbia"
 [31] "Senegal"
 [32] "Saudi Arabia"
 [33] "San Marino"
 [34] "Saint Vincent"
 [35] "Saint Lucia"
 [36] "Saint Kitts and Nevis"
 [37] "Rwanda"
 [38] "Russia"
 [39] "Romania"
 [40] "Qatar"
 [41] "Portugal"
 [42] "Poland"
 [43] "Philippines"
 [44] "Peru"
 [45] "Paraguay"
 [46] "Papua New Guinea"
 [47] "Panama"
 [48] "Palestine"
 [49] "Pakistan"
 [50] "Oman"
 [51] "Norway"
 [52] "Northern Cyprus[k]"
 [53] "North Macedonia"
 [54] "North Korea"
 [55] "Nigeria"
 [56] "Niger"
 [57] "New Zealand"
 [58] "New Caledonia"
 [59] "Netherlands"
 [60] "Nepal"
 [61] "Namibia"
 [62] "Myanmar"
 [63] "Mozambique"
 [64] "Morocco"
 [65] "Montenegro"
 [66] "Mongolia"
 [67] "Moldova[j]"
 [68] "Mexico"
 [69] "Mauritius"
 [70] "Mauritania"
 [71] "Malta"
 [72] "Mali"
 [73] "Maldives"
 [74] "Malaysia"
 [75] "Malawi"
 [76] "Madagascar"
 [77] "Luxembourg[i]"
 [78] "Lithuania"
 [79] "Libya"
 [80] "Liberia"
 [81] "Lesotho"
 [82] "Lebanon"
 [83] "Latvia"
 [84] "Laos"
 [85] "Kyrgyzstan"
 [86] "Kuwait"
 [87] "Kosovo"
 [88] "Kenya"
 [89] "Kazakhstan"
 [90] "Jordan"
 [91] "Japan"
 [92] "Jamaica"
 [93] "Ivory Coast"
 [94] "Italy"
 [95] "Israel"
 [96] "Ireland"
 [97] "Iraq"
 [98] "Iran"
 [99] "Indonesia"
[100] "India"
[101] "Iceland"
[102] "Hungary"
[103] "Honduras"
[104] "Haiti"
[105] "Guyana"
[106] "Guinea-Bissau"
[107] "Guinea"
[108] "Guatemala"
[109] "Grenada"
[110] "Greenland"
[111] "Greece"
[112] "Ghana"
[113] "Germany"
[114] "Georgia[h]"
[115] "Gambia"
[116] "Gabon"
[117] "France[f][g]"
[118] "Finland"
[119] "Fiji"
[120] "Faroe Islands"
[121] "Ethiopia"
[122] "Eswatini"
[123] "Estonia"
[124] "Equatorial Guinea"
[125] "El Salvador"
[126] "Egypt"
[127] "Ecuador"
[128] "DR Congo"
[129] "Dominican Republic"
[130] "Dominica"
[131] "Djibouti"
[132] "Denmark[e]"
[133] "Czechia"
[134] "Cyprus[d]"
[135] "Cuba"
[136] "Croatia"
[137] "Costa Rica"
[138] "Colombia"
[139] "China[c]"
[140] "Chile"
[141] "Chad"
[142] "Canada"
[143] "Cameroon"
[144] "Cambodia"
[145] "Burundi"
[146] "Burkina Faso"
[147] "Bulgaria"
[148] "Brunei"
[149] "Brazil"
[150] "Botswana"
[151] "Bosnia and Herzegovina"
[152] "Bolivia"
[153] "Bhutan"
[154] "Benin"
[155] "Belize"
[156] "Belgium"
[157] "Belarus"
[158] "Barbados"
[159] "Bangladesh"
[160] "Bahrain"
[161] "Bahamas"
[162] "Azerbaijan"
[163] "Austria"
[164] "Australia"
[165] "Armenia"
[166] "Argentina"
[167] "Antigua and Barbuda"
[168] "Angola"
[169] "Andorra"
[170] "Algeria"
[171] "Albania"
[172] "Afghanistan"
[173] ".mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}body.skin-vector-2022 .mw-parser-output .reflist-columns-2{column-width:27em}body.skin-vector-2022 .mw-parser-output .reflist-columns-3{column-width:22.5em}.mw-parser-output .references[data-mw-group=upper-alpha]{list-style-type:upper-alpha}.mw-parser-output .references[data-mw-group=upper-roman]{list-style-type:upper-roman}.mw-parser-output .references[data-mw-group=lower-alpha]{list-style-type:lower-alpha}.mw-parser-output .references[data-mw-group=lower-greek]{list-style-type:lower-greek}.mw-parser-output .references[data-mw-group=lower-roman]{list-style-type:lower-roman}.mw-parser-output div.reflist-liststyle-upper-alpha .references{list-style-type:upper-alpha}.mw-parser-output div.reflist-liststyle-upper-roman .references{list-style-type:upper-roman}.mw-parser-output div.reflist-liststyle-lower-alpha .references{list-style-type:lower-alpha}.mw-parser-output div.reflist-liststyle-lower-greek .references{list-style-type:lower-greek}.mw-parser-output div.reflist-liststyle-lower-roman .references{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member."
  [1] "Zimbabwe"
  [2] "Zambia"
  [3] "Vietnam"
  [4] "Venezuela"
  [5] "Uzbekistan"
  [6] "Uruguay"
  [7] "United States"
  [8] "United Kingdom"
  [9] "United Arab Emirates"
 [10] "Ukraine"
 [11] "Uganda"
 [12] "Turkey"
 [13] "Tunisia"
 [14] "Trinidad and Tobago"
 [15] "Togo"
 [16] "Thailand"
 [17] "Tanzania"
 [18] "Taiwan[m]"
 [19] "Switzerland[l]"
 [20] "Sweden"
 [21] "Sudan"
 [22] "Sri Lanka"
 [23] "Spain"
 [24] "South Sudan"
 [25] "South Korea"
 [26] "South Africa"
 [27] "Slovenia"
 [28] "Slovakia"
 [29] "Singapore"
 [30] "Serbia"
 [31] "Senegal"
 [32] "Saudi Arabia"
 [33] "San Marino"
 [34] "Saint Vincent"
 [35] "Saint Lucia"
 [36] "Saint Kitts and Nevis"
 [37] "Rwanda"
 [38] "Russia"
 [39] "Romania"
 [40] "Qatar"
 [41] "Portugal"
 [42] "Poland"
 [43] "Philippines"
 [44] "Peru"
 [45] "Paraguay"
 [46] "Papua New Guinea"
 [47] "Panama"
 [48] "Palestine"
 [49] "Pakistan"
 [50] "Oman"
 [51] "Norway"
 [52] "Northern Cyprus[k]"
 [53] "North Macedonia"
 [54] "North Korea"
 [55] "Nigeria"
 [56] "Niger"
 [57] "New Zealand"
 [58] "New Caledonia"
 [59] "Netherlands"
 [60] "Nepal"
 [61] "Namibia"
 [62] "Myanmar"
 [63] "Mozambique"
 [64] "Morocco"
 [65] "Montenegro"
 [66] "Mongolia"
 [67] "Moldova[j]"
 [68] "Mexico"
 [69] "Mauritius"
 [70] "Mauritania"
 [71] "Malta"
 [72] "Mali"
 [73] "Maldives"
 [74] "Malaysia"
 [75] "Malawi"
 [76] "Madagascar"
 [77] "Luxembourg[i]"
 [78] "Lithuania"
 [79] "Libya"
 [80] "Liberia"
 [81] "Lesotho"
 [82] "Lebanon"
 [83] "Latvia"
 [84] "Laos"
 [85] "Kyrgyzstan"
 [86] "Kuwait"
 [87] "Kosovo"
 [88] "Kenya"
 [89] "Kazakhstan"
 [90] "Jordan"
 [91] "Japan"
 [92] "Jamaica"
 [93] "Ivory Coast"
 [94] "Italy"
 [95] "Israel"
 [96] "Ireland"
 [97] "Iraq"
 [98] "Iran"
 [99] "Indonesia"
[100] "India"
[101] "Iceland"
[102] "Hungary"
[103] "Honduras"
[104] "Haiti"
[105] "Guyana"
[106] "Guinea-Bissau"
[107] "Guinea"
[108] "Guatemala"
[109] "Grenada"
[110] "Greenland"
[111] "Greece"
[112] "Ghana"
[113] "Germany"
[114] "Georgia[h]"
[115] "Gambia"
[116] "Gabon"
[117] "France[f][g]"
[118] "Finland"
[119] "Fiji"
[120] "Faroe Islands"
[121] "Ethiopia"
[122] "Eswatini"
[123] "Estonia"
[124] "Equatorial Guinea"
[125] "El Salvador"
[126] "Egypt"
[127] "Ecuador"
[128] "DR Congo"
[129] "Dominican Republic"
[130] "Dominica"
[131] "Djibouti"
[132] "Denmark[e]"
[133] "Czechia"
[134] "Cyprus[d]"
[135] "Cuba"
[136] "Croatia"
[137] "Costa Rica"
[138] "Colombia"
[139] "China[c]"
[140] "Chile"
[141] "Chad"
[142] "Canada"
[143] "Cameroon"
[144] "Cambodia"
[145] "Burundi"
[146] "Burkina Faso"
[147] "Bulgaria"
[148] "Brunei"
[149] "Brazil"
[150] "Botswana"
[151] "Bosnia and Herzegovina"
[152] "Bolivia"
[153] "Bhutan"
[154] "Benin"
[155] "Belize"
[156] "Belgium"
[157] "Belarus"
[158] "Barbados"
[159] "Bangladesh"
[160] "Bahrain"
[161] "Bahamas"
[162] "Azerbaijan"
[163] "Austria"
[164] "Australia"
[165] "Armenia"
[166] "Argentina"
[167] "Antigua and Barbuda"
[168] "Angola"
[169] "Andorra"
[170] "Algeria"
[171] "Albania"
[172] "Afghanistan"
[173] ".mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}body.skin-vector-2022 .mw-parser-output .reflist-columns-2{column-width:27em}body.skin-vector-2022 .mw-parser-output .reflist-columns-3{column-width:22.5em}.mw-parser-output .references[data-mw-group=upper-alpha]{list-style-type:upper-alpha}.mw-parser-output .references[data-mw-group=upper-roman]{list-style-type:upper-roman}.mw-parser-output .references[data-mw-group=lower-alpha]{list-style-type:lower-alpha}.mw-parser-output .references[data-mw-group=lower-greek]{list-style-type:lower-greek}.mw-parser-output .references[data-mw-group=lower-roman]{list-style-type:lower-roman}.mw-parser-output div.reflist-liststyle-upper-alpha .references{list-style-type:upper-alpha}.mw-parser-output div.reflist-liststyle-upper-roman .references{list-style-type:upper-roman}.mw-parser-output div.reflist-liststyle-lower-alpha .references{list-style-type:lower-alpha}.mw-parser-output div.reflist-liststyle-lower-greek .references{list-style-type:lower-greek}.mw-parser-output div.reflist-liststyle-lower-roman .references{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member."

## TASK 7: Identify countries names with a specific pattern

The goal of task 7 is using a regular expression to find any countires start with `United`

In [17]:
# Use a regular expression `United.+` to find matches
matched_countries <- grep(
  "United.+",
  covid_data_frame_csv$country,
  value = TRUE
)
print(matched_countries)

# Print the matched country names
matched_countries <- grep(
  "United.+",
  covid_data_frame_csv$country,
  value = TRUE
)

print(matched_countries)

[1] "United Arab Emirates"
[2] "United Kingdom"
[3] "United States"
[4] ".mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}body.skin-vector-2022 .mw-parser-output .reflist-columns-2{column-width:27em}body.skin-vector-2022 .mw-parser-output .reflist-columns-3{column-width:22.5em}.mw-parser-output .references[data-mw-group=upper-alpha]{list-style-type:upper-alpha}.mw-parser-output .references[data-mw-group=upper-roman]{list-style-type:upper-roman}.mw-parser-output .references[data-mw-group=lower-alpha]{list-style-type:lower-alpha}.mw-parser-output .references[data-mw-group=lower-greek]{list-style-type:lower-greek}.mw-parser-output .references[data-mw-group=lower-roman]{list-style-type:lower-roman}.mw-parser-output div.reflist-liststyle-upper-alpha .references{list-style-type:upper-alpha}.mw-parser-output div.reflist-liststyle-upper-roman .references{list-style-type:upper-roman}.mw-parser-output div.reflist-liststyle-lower-alpha .references{list-style-type:lower-alpha}.mw-parser-output div.reflist-liststyle-lower-greek .references{list-style-type:lower-greek}.mw-parser-output div.reflist-liststyle-lower-roman .references{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member."
[1] "United Arab Emirates"
[2] "United Kingdom"
[3] "United States"
[4] ".mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}body.skin-vector-2022 .mw-parser-output .reflist-columns-2{column-width:27em}body.skin-vector-2022 .mw-parser-output .reflist-columns-3{column-width:22.5em}.mw-parser-output .references[data-mw-group=upper-alpha]{list-style-type:upper-alpha}.mw-parser-output .references[data-mw-group=upper-roman]{list-style-type:upper-roman}.mw-parser-output .references[data-mw-group=lower-alpha]{list-style-type:lower-alpha}.mw-parser-output .references[data-mw-group=lower-greek]{list-style-type:lower-greek}.mw-parser-output .references[data-mw-group=lower-roman]{list-style-type:lower-roman}.mw-parser-output div.reflist-liststyle-upper-alpha .references{list-style-type:upper-alpha}.mw-parser-output div.reflist-liststyle-upper-roman .references{list-style-type:upper-roman}.mw-parser-output div.reflist-liststyle-lower-alpha .references{list-style-type:lower-alpha}.mw-parser-output div.reflist-liststyle-lower-greek .references{list-style-type:lower-greek}.mw-parser-output div.reflist-liststyle-lower-roman .references{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member."

## TASK 8: Pick two countries you are interested, and then review their testing data

The goal of task 8 is to compare the COVID-19 test data between two countires, you will need to select two rows from the dataframe, and select `country`, `confirmed`, `confirmed-population-ratio` columns

In [18]:
# Select a subset (should be only one row) of data frame based on a selected country name and columns
selected_country <- "Canada"

country_subset <- subset(
  covid_data_frame_csv,
  country == selected_country,
  select = c(country, confirmed, tested)
)

print(country_subset)

# Select a subset (should be only one row) of data frame based on a selected country name and columns

selected_country <- "United States"

country_subset <- subset(
  covid_data_frame_csv,
  country == selected_country,
  select = c(country,
             confirmed,
             tested,
             confirmed.population.ratio)
)

   country confirmed   tested
31  Canada        NA 66343123

## TASK 9: Compare which one of the selected countries has a larger ratio of confirmed cases to population

The goal of task 9 is to find out which country you have selected before has larger ratio of confirmed cases to population, which may indicate that country has higher COVID-19 infection risk

In [19]:
# Use if-else statement
# if (check which confirmed.population value is greater) {
#    print()
# } else {
#    print()
# }

# Compare two countries by confirmed.population.ratio
# Select countries to compare
country1 <- "Canada"
country2 <- "United States"

# Extract confirmed.population.ratio values
ratio1 <- subset(
  covid_data_frame_csv,
  country == country1,
  select = confirmed.population.ratio
)$confirmed.population.ratio

ratio2 <- subset(
  covid_data_frame_csv,
  country == country2,
  select = confirmed.population.ratio
)$confirmed.population.ratio

# Use if-else statement
if (ratio1 > ratio2) {
  
  print(
    paste(
      country1,
      "has a higher confirmed cases to population ratio than",
      country2
    )
  )
  
} else if (ratio2 > ratio1) {
  
  print(
    paste(
      country2,
      "has a higher confirmed cases to population ratio than",
      country1
    )
  )
  
} else {
  
  print(
    paste(
      country1,
      "and",
      country2,
      "have the same confirmed cases to population ratio"
    )
  )
  
}

[1] "United States has a higher confirmed cases to population ratio than Canada"

## TASK 10: Find countries with confirmed to population ratio rate less than a threshold

The goal of task 10 is to find out which countries have the confirmed to population ratio less than 1%, it may indicate the risk of those countries are relatively low

In [20]:
# Get a subset of any countries with `confirmed.population.ratio` less than the threshold
# Define threshold (you can change this value as needed)
threshold <- 0.1

# Get subset of countries with confirmed.population.ratio less than threshold
low_risk_countries <- subset(
  covid_data_frame_csv,
  confirmed.population.ratio < threshold,
  select = c(country,
             confirmed,
             tested,
             confirmed.population.ratio)
)

# Print result
print(low_risk_countries)

        country confirmed tested confirmed.population.ratio
119 North Korea        NA  16914                     0.0660
156    Tanzania        NA   3880                     0.0065